// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.switchapi.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class AnnouncementsService {
    private final ProductCore core;

    AnnouncementsService(ProductCore core) {
        this.core = core;
    }

    /** POST /announcements */
    public String createAnnouncement(String name, String sounddata) throws IOException, InterruptedException {
        Objects.requireNonNull(name, "name");
        Objects.requireNonNull(sounddata, "sounddata");
        CallParts call = new CallParts();
        call.form("name", name);
        call.form("sounddata", sounddata);
        TransportResponse reply = core.send(RawOperations.CREATE_ANNOUNCEMENT, call);
        return ResponseReader.text(reply);
    }

    /** DELETE /announcements/{id} */
    public String deleteAnnouncement(String id) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        CallParts call = new CallParts();
        call.path("id", id);
        TransportResponse reply = core.send(RawOperations.DELETE_ANNOUNCEMENT, call);
        return ResponseReader.text(reply);
    }

    /** GET /announcements */
    public List<GetAnnouncements200ResponseInner> listAnnouncements() throws IOException, InterruptedException {
        CallParts call = new CallParts();
        TransportResponse reply = core.send(RawOperations.GET_ANNOUNCEMENTS, call);
        return ResponseReader.json(reply, new TypeReference<List<GetAnnouncements200ResponseInner>>() { });
    }

    /** PATCH /announcements/{id} */
    public String updateAnnouncement(String id, @Nullable String name, @Nullable String sounddata) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        CallParts call = new CallParts();
        call.path("id", id);
        call.form("name", name);
        call.form("sounddata", sounddata);
        TransportResponse reply = core.send(RawOperations.UPDATE_ANNOUNCEMENT, call);
        return ResponseReader.text(reply);
    }

    /** PATCH /announcements/{id} without the optional parameters. */
    public String updateAnnouncement(String id) throws IOException, InterruptedException {
        return updateAnnouncement(id, null, null);
    }
}
