// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.switchapi.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class BlacklistService {
    private final ProductCore core;

    BlacklistService(ProductCore core) {
        this.core = core;
    }

    /** POST /blocked_numbers */
    public String createBlockedNumber(String number, @Nullable String direction) throws IOException, InterruptedException {
        Objects.requireNonNull(number, "number");
        CallParts call = new CallParts();
        call.query("number", number);
        call.query("direction", direction);
        TransportResponse reply = core.send(RawOperations.CREATE_BLOCKED_NUMBER, call);
        return ResponseReader.text(reply);
    }

    /** POST /blocked_numbers without the optional parameters. */
    public String createBlockedNumber(String number) throws IOException, InterruptedException {
        return createBlockedNumber(number, null);
    }

    /** DELETE /blocked_numbers/delete */
    public String deleteBlockedNumber(String number, @Nullable String direction) throws IOException, InterruptedException {
        Objects.requireNonNull(number, "number");
        CallParts call = new CallParts();
        call.query("number", number);
        call.query("direction", direction);
        TransportResponse reply = core.send(RawOperations.DELETE_BLOCKED_NUMBER, call);
        return ResponseReader.text(reply);
    }

    /** DELETE /blocked_numbers/delete without the optional parameters. */
    public String deleteBlockedNumber(String number) throws IOException, InterruptedException {
        return deleteBlockedNumber(number, null);
    }

    /** GET /blocked_numbers */
    public ListBlockedNumbers200Response listBlockedNumbers(@Nullable Long page, @Nullable Long limit) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("page", page);
        call.query("limit", limit);
        TransportResponse reply = core.send(RawOperations.LIST_BLOCKED_NUMBERS, call);
        return ResponseReader.json(reply, ListBlockedNumbers200Response.class);
    }

    /** GET /blocked_numbers without the optional parameters. */
    public ListBlockedNumbers200Response listBlockedNumbers() throws IOException, InterruptedException {
        return listBlockedNumbers(null, null);
    }
}
