// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.switchapi.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class CallerIdsService {
    private final ProductCore core;

    CallerIdsService(ProductCore core) {
        this.core = core;
    }

    /** GET /caller_ids */
    public List<String> listCallerIds() throws IOException, InterruptedException {
        CallParts call = new CallParts();
        TransportResponse reply = core.send(RawOperations.GET_CALLER_IDS, call);
        return ResponseReader.json(reply, new TypeReference<List<String>>() { });
    }

    /** GET /update_outbound_caller_id */
    public String updateOutboundCallerId(String extension, String callerId) throws IOException, InterruptedException {
        Objects.requireNonNull(extension, "extension");
        Objects.requireNonNull(callerId, "callerId");
        CallParts call = new CallParts();
        call.query("extension", extension);
        call.query("caller_id", callerId);
        TransportResponse reply = core.send(RawOperations.UPDATE_OUTBOUND_CALLER_ID, call);
        return ResponseReader.text(reply);
    }
}
