// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.switchapi.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class CallsService {
    private final ProductCore core;

    CallsService(ProductCore core) {
        this.core = core;
    }

    /** POST /answer */
    public String answer(AnswerCallPostRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.ANSWER_CALL_POST, call);
        return ResponseReader.text(reply);
    }

    /** GET /answer/{id} */
    public String answerLegacy(String id) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        CallParts call = new CallParts();
        call.path("id", id);
        TransportResponse reply = core.send(RawOperations.ANSWER_CALL, call);
        return ResponseReader.text(reply);
    }

    /** GET /bridge */
    public String bridge(String source, String destination, @Nullable String callerId, @Nullable Long timeout, @Nullable Long announcementToCaller, @Nullable Long announcementToCallee, @Nullable Boolean recordingEnabled) throws IOException, InterruptedException {
        Objects.requireNonNull(source, "source");
        Objects.requireNonNull(destination, "destination");
        CallParts call = new CallParts();
        call.query("source", source);
        call.query("destination", destination);
        call.query("caller_id", callerId);
        call.query("timeout", timeout);
        call.query("announcement_to_caller", announcementToCaller);
        call.query("announcement_to_callee", announcementToCallee);
        call.query("recording_enabled", recordingEnabled);
        TransportResponse reply = core.send(RawOperations.CREATE_BRIDGE, call);
        return ResponseReader.text(reply);
    }

    /** GET /bridge without the optional parameters. */
    public String bridge(String source, String destination) throws IOException, InterruptedException {
        return bridge(source, destination, null, null, null, null, null);
    }

    /** GET /hangup/{id} */
    public String hangup(String id) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        CallParts call = new CallParts();
        call.path("id", id);
        TransportResponse reply = core.send(RawOperations.HANGUP_CALL, call);
        return ResponseReader.text(reply);
    }

    /** POST /originate */
    public String originate(OriginateCallPostRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.ORIGINATE_CALL_POST, call);
        return ResponseReader.text(reply);
    }

    /** GET /originate */
    public String originateLegacy(String extension, String destination, @Nullable String callerId, @Nullable Boolean manualAnswer, @Nullable Long timeout, @Nullable Long announcementToCallee, @Nullable Long announcementToCaller, @Nullable String customCallType) throws IOException, InterruptedException {
        Objects.requireNonNull(extension, "extension");
        Objects.requireNonNull(destination, "destination");
        CallParts call = new CallParts();
        call.query("extension", extension);
        call.query("destination", destination);
        call.query("caller_id", callerId);
        call.query("manual_answer", manualAnswer);
        call.query("timeout", timeout);
        call.query("announcement_to_callee", announcementToCallee);
        call.query("announcement_to_caller", announcementToCaller);
        call.query("custom_call_type", customCallType);
        TransportResponse reply = core.send(RawOperations.ORIGINATE_CALL, call);
        return ResponseReader.text(reply);
    }

    /** GET /originate without the optional parameters. */
    public String originateLegacy(String extension, String destination) throws IOException, InterruptedException {
        return originateLegacy(extension, destination, null, null, null, null, null, null);
    }

    /** GET /mute/{id} */
    public String setCallMute(String id, String state) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        Objects.requireNonNull(state, "state");
        CallParts call = new CallParts();
        call.path("id", id);
        call.query("state", state);
        TransportResponse reply = core.send(RawOperations.MUTE_CALL, call);
        return ResponseReader.text(reply);
    }

    /** POST /transfer */
    public String transfer(String id, String userNumber) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        Objects.requireNonNull(userNumber, "userNumber");
        CallParts call = new CallParts();
        call.query("id", id);
        call.query("user_number", userNumber);
        TransportResponse reply = core.send(RawOperations.TRANSFER_CALL_POST, call);
        return ResponseReader.text(reply);
    }

    /** GET /transfer/{id} */
    public String transferLegacy(String id, String userNumber) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        Objects.requireNonNull(userNumber, "userNumber");
        CallParts call = new CallParts();
        call.path("id", id);
        call.query("user_number", userNumber);
        TransportResponse reply = core.send(RawOperations.TRANSFER_CALL, call);
        return ResponseReader.text(reply);
    }
}
