// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.switchapi.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class ContactsService {
    private final ProductCore core;

    ContactsService(ProductCore core) {
        this.core = core;
    }

    /** POST /contacts */
    public String createContact(String name, String surname, String phone, @Nullable String salutation, @Nullable String tckn, @Nullable String description, @Nullable String phone1, @Nullable String email, @Nullable String title, @Nullable String phone2, @Nullable String fax, @Nullable String gender, @Nullable String birthday, @Nullable Boolean birthdaySms, @Nullable String weddingday, @Nullable Boolean weddingdaySms, @Nullable String address, @Nullable String note1, @Nullable String note2, @Nullable String note3, @Nullable String note4, @Nullable String companyName, @Nullable Long monthlySmsDay, @Nullable String monthlySmsMessage, @Nullable List<Long> groupIds) throws IOException, InterruptedException {
        Objects.requireNonNull(name, "name");
        Objects.requireNonNull(surname, "surname");
        Objects.requireNonNull(phone, "phone");
        CallParts call = new CallParts();
        call.query("name", name);
        call.query("surname", surname);
        call.query("phone", phone);
        call.query("salutation", salutation);
        call.query("tckn", tckn);
        call.query("description", description);
        call.query("phone1", phone1);
        call.query("email", email);
        call.query("title", title);
        call.query("phone2", phone2);
        call.query("fax", fax);
        call.query("gender", gender);
        call.query("birthday", birthday);
        call.query("birthday_sms", birthdaySms);
        call.query("weddingday", weddingday);
        call.query("weddingday_sms", weddingdaySms);
        call.query("address", address);
        call.query("note1", note1);
        call.query("note2", note2);
        call.query("note3", note3);
        call.query("note4", note4);
        call.query("company_name", companyName);
        call.query("monthly_sms_day", monthlySmsDay);
        call.query("monthly_sms_message", monthlySmsMessage);
        call.query("group_ids", groupIds);
        TransportResponse reply = core.send(RawOperations.CREATE_CONTACT, call);
        return ResponseReader.text(reply);
    }

    /** POST /contacts without the optional parameters. */
    public String createContact(String name, String surname, String phone) throws IOException, InterruptedException {
        return createContact(name, surname, phone, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
    }

    /** POST /contact_groups */
    public String createContactGroup(String name) throws IOException, InterruptedException {
        Objects.requireNonNull(name, "name");
        CallParts call = new CallParts();
        call.query("name", name);
        TransportResponse reply = core.send(RawOperations.CREATE_CONTACT_GROUP, call);
        return ResponseReader.text(reply);
    }

    /** DELETE /contacts/{id} */
    public String deleteContact(long id) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.path("id", id);
        TransportResponse reply = core.send(RawOperations.DELETE_CONTACT, call);
        return ResponseReader.text(reply);
    }

    /** DELETE /contact_groups/{id} */
    public String deleteContactGroup(long id) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.path("id", id);
        TransportResponse reply = core.send(RawOperations.DELETE_CONTACT_GROUP, call);
        return ResponseReader.text(reply);
    }

    /** GET /contact_groups */
    public List<ListContactGroups200ResponseInner> listContactGroups() throws IOException, InterruptedException {
        CallParts call = new CallParts();
        TransportResponse reply = core.send(RawOperations.LIST_CONTACT_GROUPS, call);
        return ResponseReader.json(reply, new TypeReference<List<ListContactGroups200ResponseInner>>() { });
    }

    /** GET /contacts */
    public ListContacts200Response listContacts(@Nullable Long page, @Nullable Long limit) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("page", page);
        call.query("limit", limit);
        TransportResponse reply = core.send(RawOperations.LIST_CONTACTS, call);
        return ResponseReader.json(reply, ListContacts200Response.class);
    }

    /** GET /contacts without the optional parameters. */
    public ListContacts200Response listContacts() throws IOException, InterruptedException {
        return listContacts(null, null);
    }

    /** PATCH /contacts/{id} */
    public String updateContact(long id, @Nullable String salutation, @Nullable String name, @Nullable String surname, @Nullable String tckn, @Nullable String description, @Nullable String phone, @Nullable String phone1, @Nullable String email, @Nullable String title, @Nullable String phone2, @Nullable String fax, @Nullable String gender, @Nullable String birthday, @Nullable Boolean birthdaySms, @Nullable String weddingday, @Nullable Boolean weddingdaySms, @Nullable String address, @Nullable String note1, @Nullable String note2, @Nullable String note3, @Nullable String note4, @Nullable String companyName, @Nullable Long monthlySmsDay, @Nullable String monthlySmsMessage, @Nullable List<Long> groupIds) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.path("id", id);
        call.query("salutation", salutation);
        call.query("name", name);
        call.query("surname", surname);
        call.query("tckn", tckn);
        call.query("description", description);
        call.query("phone", phone);
        call.query("phone1", phone1);
        call.query("email", email);
        call.query("title", title);
        call.query("phone2", phone2);
        call.query("fax", fax);
        call.query("gender", gender);
        call.query("birthday", birthday);
        call.query("birthday_sms", birthdaySms);
        call.query("weddingday", weddingday);
        call.query("weddingday_sms", weddingdaySms);
        call.query("address", address);
        call.query("note1", note1);
        call.query("note2", note2);
        call.query("note3", note3);
        call.query("note4", note4);
        call.query("company_name", companyName);
        call.query("monthly_sms_day", monthlySmsDay);
        call.query("monthly_sms_message", monthlySmsMessage);
        call.query("group_ids", groupIds);
        TransportResponse reply = core.send(RawOperations.UPDATE_CONTACT, call);
        return ResponseReader.text(reply);
    }

    /** PATCH /contacts/{id} without the optional parameters. */
    public String updateContact(long id) throws IOException, InterruptedException {
        return updateContact(id, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
    }

    /** PATCH /contact_groups/{id} */
    public String updateContactGroup(long id, String name) throws IOException, InterruptedException {
        Objects.requireNonNull(name, "name");
        CallParts call = new CallParts();
        call.path("id", id);
        call.query("name", name);
        TransportResponse reply = core.send(RawOperations.UPDATE_CONTACT_GROUP, call);
        return ResponseReader.text(reply);
    }
}
