// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.switchapi.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class CrmService {
    private final ProductCore core;

    CrmService(ProductCore core) {
        this.core = core;
    }

    /** GET /crm_integrations */
    public GetCrmIntegrations200Response getCrmIntegrations() throws IOException, InterruptedException {
        CallParts call = new CallParts();
        TransportResponse reply = core.send(RawOperations.GET_CRM_INTEGRATIONS, call);
        return ResponseReader.json(reply, GetCrmIntegrations200Response.class);
    }

    /** GET /webhook-payload-examples */
    public WebhookPayloadExamples200Response getWebhookPayloadExamples() throws IOException, InterruptedException {
        CallParts call = new CallParts();
        TransportResponse reply = core.send(RawOperations.WEBHOOK_PAYLOAD_EXAMPLES, call);
        return ResponseReader.json(reply, WebhookPayloadExamples200Response.class);
    }

    /** POST /crm_integrations */
    public String updateCrmIntegrations(@Nullable String ringing, @Nullable String answered, @Nullable String hangup, @Nullable String notificationUrl) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("ringing", ringing);
        call.query("answered", answered);
        call.query("hangup", hangup);
        call.query("notification_url", notificationUrl);
        TransportResponse reply = core.send(RawOperations.UPDATE_CRM_INTEGRATIONS, call);
        return ResponseReader.text(reply);
    }

    /** POST /crm_integrations without the optional parameters. */
    public String updateCrmIntegrations() throws IOException, InterruptedException {
        return updateCrmIntegrations(null, null, null, null);
    }
}
