// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.switchapi.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class FaxService {
    private final ProductCore core;

    FaxService(ProductCore core) {
        this.core = core;
    }

    /** POST /fax_document_url */
    public String createFaxDocumentUrl(String callUuid) throws IOException, InterruptedException {
        Objects.requireNonNull(callUuid, "callUuid");
        CallParts call = new CallParts();
        call.query("call_uuid", callUuid);
        TransportResponse reply = core.send(RawOperations.CREATE_FAX_DOCUMENT_URL, call);
        return ResponseReader.text(reply);
    }

    /** POST /fax_orders */
    public String createFaxOrder(String remoteStationId, String filedata, @Nullable String localStationId, @Nullable String localStationHeader) throws IOException, InterruptedException {
        Objects.requireNonNull(remoteStationId, "remoteStationId");
        Objects.requireNonNull(filedata, "filedata");
        CallParts call = new CallParts();
        call.query("remote_station_id", remoteStationId);
        call.query("filedata", filedata);
        call.query("local_station_id", localStationId);
        call.query("local_station_header", localStationHeader);
        TransportResponse reply = core.send(RawOperations.CREATE_FAX_ORDER, call);
        return ResponseReader.text(reply);
    }

    /** POST /fax_orders without the optional parameters. */
    public String createFaxOrder(String remoteStationId, String filedata) throws IOException, InterruptedException {
        return createFaxOrder(remoteStationId, filedata, null, null);
    }

    /** GET /fax_document/{id} */
    public byte[] downloadFaxDocument(String id) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        CallParts call = new CallParts();
        call.path("id", id);
        TransportResponse reply = core.send(RawOperations.DOWNLOAD_FAX_DOCUMENT, call);
        return ResponseReader.bytes(reply);
    }

    /** GET /fax_orders */
    public ListFaxOrders200Response listFaxOrders(@Nullable Long page, @Nullable Long limit) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("page", page);
        call.query("limit", limit);
        TransportResponse reply = core.send(RawOperations.LIST_FAX_ORDERS, call);
        return ResponseReader.json(reply, ListFaxOrders200Response.class);
    }

    /** GET /fax_orders without the optional parameters. */
    public ListFaxOrders200Response listFaxOrders() throws IOException, InterruptedException {
        return listFaxOrders(null, null);
    }

    /** GET /fdrs */
    public ListFdrs200Response listFaxRecords(@Nullable String startStampFrom, @Nullable String startStampTo, @Nullable String direction, @Nullable String callerIdNumber, @Nullable String originalDestination, @Nullable String success, @Nullable Long page, @Nullable Long limit) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("start_stamp_from", startStampFrom);
        call.query("start_stamp_to", startStampTo);
        call.query("direction", direction);
        call.query("caller_id_number", callerIdNumber);
        call.query("original_destination", originalDestination);
        call.query("success", success);
        call.query("page", page);
        call.query("limit", limit);
        TransportResponse reply = core.send(RawOperations.LIST_FDRS, call);
        return ResponseReader.json(reply, ListFdrs200Response.class);
    }

    /** GET /fdrs without the optional parameters. */
    public ListFdrs200Response listFaxRecords() throws IOException, InterruptedException {
        return listFaxRecords(null, null, null, null, null, null, null, null);
    }
}
