// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.switchapi.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class IvrCampaignsService {
    private final ProductCore core;

    IvrCampaignsService(ProductCore core) {
        this.core = core;
    }

    /** POST /ivr_campaigns.json */
    public String createIvrCampaign(CreateIvrCampaignRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.CREATE_IVR_CAMPAIGN, call);
        return ResponseReader.text(reply);
    }

    /** DELETE /ivr_campaigns/{id}.json */
    public String deleteIvrCampaign(String id) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        CallParts call = new CallParts();
        call.path("id", id);
        TransportResponse reply = core.send(RawOperations.DELETE_IVR_CAMPAIGN, call);
        return ResponseReader.text(reply);
    }

    /** PATCH /ivr_campaigns/{id}.json */
    public String updateIvrCampaign(String id, String status) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        Objects.requireNonNull(status, "status");
        CallParts call = new CallParts();
        call.path("id", id);
        call.query("status", status);
        TransportResponse reply = core.send(RawOperations.UPDATE_IVR_CAMPAIGN, call);
        return ResponseReader.text(reply);
    }
}
