// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.switchapi.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class QueuesService {
    private final ProductCore core;

    QueuesService(ProductCore core) {
        this.core = core;
    }

    /** GET /queues/pending */
    public List<GetQueuesPending200ResponseInner> listQueuePendingCalls() throws IOException, InterruptedException {
        CallParts call = new CallParts();
        TransportResponse reply = core.send(RawOperations.GET_QUEUES_PENDING, call);
        return ResponseReader.json(reply, new TypeReference<List<GetQueuesPending200ResponseInner>>() { });
    }

    /** GET /queue/user_list */
    public List<GetQueueUserList200ResponseInner> listQueueUsers(String queueNumber) throws IOException, InterruptedException {
        Objects.requireNonNull(queueNumber, "queueNumber");
        CallParts call = new CallParts();
        call.query("queue_number", queueNumber);
        TransportResponse reply = core.send(RawOperations.GET_QUEUE_USER_LIST, call);
        return ResponseReader.json(reply, new TypeReference<List<GetQueueUserList200ResponseInner>>() { });
    }

    /** GET /queues */
    public List<GetQueues200ResponseInner> listQueues() throws IOException, InterruptedException {
        CallParts call = new CallParts();
        TransportResponse reply = core.send(RawOperations.GET_QUEUES, call);
        return ResponseReader.json(reply, new TypeReference<List<GetQueues200ResponseInner>>() { });
    }

    /** GET /queue/manage_users */
    public String manageQueueUsers(String queueNumber, String userList) throws IOException, InterruptedException {
        Objects.requireNonNull(queueNumber, "queueNumber");
        Objects.requireNonNull(userList, "userList");
        CallParts call = new CallParts();
        call.query("queue_number", queueNumber);
        call.query("user_list", userList);
        TransportResponse reply = core.send(RawOperations.MANAGE_QUEUE_USERS, call);
        return ResponseReader.text(reply);
    }
}
