// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.RawOperation;
import java.net.URI;
import java.util.List;
import java.util.Map;

public final class RawOperations {
    public static final URI DEFAULT_BASE_URI = URI.create("https://api.bulutsantralim.com/");

    public static final RawOperation ANSWER_CALL = new RawOperation(
            "answerCall",
            "GET",
            "/answer/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation ANSWER_CALL_POST = new RawOperation(
            "answerCallPost",
            "POST",
            "/answer",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_ANNOUNCEMENT = new RawOperation(
            "createAnnouncement",
            "POST",
            "/announcements",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_BLOCKED_NUMBER = new RawOperation(
            "createBlockedNumber",
            "POST",
            "/blocked_numbers",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_BRIDGE = new RawOperation(
            "createBridge",
            "GET",
            "/bridge",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_CONTACT = new RawOperation(
            "createContact",
            "POST",
            "/contacts",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_CONTACT_GROUP = new RawOperation(
            "createContactGroup",
            "POST",
            "/contact_groups",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_DND = new RawOperation(
            "createDnd",
            "GET",
            "/dnd/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_FAX_DOCUMENT_URL = new RawOperation(
            "createFaxDocumentUrl",
            "POST",
            "/fax_document_url",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_FAX_ORDER = new RawOperation(
            "createFaxOrder",
            "POST",
            "/fax_orders",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_IVR_CAMPAIGN = new RawOperation(
            "createIvrCampaign",
            "POST",
            "/ivr_campaigns.json",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_RECORDING_URL = new RawOperation(
            "createRecordingUrl",
            "POST",
            "/recording_url",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_VOICEMAIL_RECORDING_URL = new RawOperation(
            "createVoicemailRecordingUrl",
            "POST",
            "/voicemail_recording_url",
            Map.of("key", "query"),
            null);

    public static final RawOperation CREATE_WEBPHONE_TOKEN = new RawOperation(
            "createWebphoneToken",
            "POST",
            "/webphone_tokens",
            Map.of("key", "query"),
            null);

    public static final RawOperation DELETE_ANNOUNCEMENT = new RawOperation(
            "deleteAnnouncement",
            "DELETE",
            "/announcements/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation DELETE_BLOCKED_NUMBER = new RawOperation(
            "deleteBlockedNumber",
            "DELETE",
            "/blocked_numbers/delete",
            Map.of("key", "query"),
            null);

    public static final RawOperation DELETE_CONTACT = new RawOperation(
            "deleteContact",
            "DELETE",
            "/contacts/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation DELETE_CONTACT_GROUP = new RawOperation(
            "deleteContactGroup",
            "DELETE",
            "/contact_groups/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation DELETE_IVR_CAMPAIGN = new RawOperation(
            "deleteIvrCampaign",
            "DELETE",
            "/ivr_campaigns/{id}.json",
            Map.of("key", "query"),
            null);

    public static final RawOperation DOWNLOAD_FAX_DOCUMENT = new RawOperation(
            "downloadFaxDocument",
            "GET",
            "/fax_document/{id}",
            Map.of(),
            null);

    public static final RawOperation GET_ANNOUNCEMENTS = new RawOperation(
            "getAnnouncements",
            "GET",
            "/announcements",
            Map.of("key", "query"),
            null);

    public static final RawOperation GET_CALLER_IDS = new RawOperation(
            "getCallerIds",
            "GET",
            "/caller_ids",
            Map.of("key", "query"),
            null);

    public static final RawOperation GET_CDR = new RawOperation(
            "getCdr",
            "GET",
            "/cdrs/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation GET_CDRS = new RawOperation(
            "getCdrs",
            "GET",
            "/cdrs",
            Map.of("key", "query"),
            null);

    public static final RawOperation GET_CRM_INTEGRATIONS = new RawOperation(
            "getCrmIntegrations",
            "GET",
            "/crm_integrations",
            Map.of("key", "query"),
            null);

    public static final RawOperation GET_EXTENSION = new RawOperation(
            "getExtension",
            "GET",
            "/extensions/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation GET_QUEUE_USER_LIST = new RawOperation(
            "getQueueUserList",
            "GET",
            "/queue/user_list",
            Map.of("key", "query"),
            null);

    public static final RawOperation GET_QUEUES = new RawOperation(
            "getQueues",
            "GET",
            "/queues",
            Map.of("key", "query"),
            null);

    public static final RawOperation GET_QUEUES_PENDING = new RawOperation(
            "getQueuesPending",
            "GET",
            "/queues/pending",
            Map.of("key", "query"),
            null);

    public static final RawOperation GET_VOICEMAIL_MESSAGES = new RawOperation(
            "getVoicemailMessages",
            "GET",
            "/voicemail_messages",
            Map.of("key", "query"),
            null);

    public static final RawOperation HANGUP_CALL = new RawOperation(
            "hangupCall",
            "GET",
            "/hangup/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation LIST_AGENT_STATUSES = new RawOperation(
            "listAgentStatuses",
            "GET",
            "/agent_statuses",
            Map.of("key", "query"),
            null);

    public static final RawOperation LIST_BLOCKED_NUMBERS = new RawOperation(
            "listBlockedNumbers",
            "GET",
            "/blocked_numbers",
            Map.of("key", "query"),
            null);

    public static final RawOperation LIST_CONTACT_GROUPS = new RawOperation(
            "listContactGroups",
            "GET",
            "/contact_groups",
            Map.of("key", "query"),
            null);

    public static final RawOperation LIST_CONTACTS = new RawOperation(
            "listContacts",
            "GET",
            "/contacts",
            Map.of("key", "query"),
            null);

    public static final RawOperation LIST_EXTENSIONS = new RawOperation(
            "listExtensions",
            "GET",
            "/extensions",
            Map.of("key", "query"),
            null);

    public static final RawOperation LIST_FAX_ORDERS = new RawOperation(
            "listFaxOrders",
            "GET",
            "/fax_orders",
            Map.of("key", "query"),
            null);

    public static final RawOperation LIST_FDRS = new RawOperation(
            "listFdrs",
            "GET",
            "/fdrs",
            Map.of("key", "query"),
            null);

    public static final RawOperation LIST_USER_STATUSES = new RawOperation(
            "listUserStatuses",
            "GET",
            "/user_statuses",
            Map.of("key", "query"),
            null);

    public static final RawOperation MANAGE_QUEUE_USERS = new RawOperation(
            "manageQueueUsers",
            "GET",
            "/queue/manage_users",
            Map.of("key", "query"),
            null);

    public static final RawOperation MUTE_CALL = new RawOperation(
            "muteCall",
            "GET",
            "/mute/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation ORIGINATE_CALL = new RawOperation(
            "originateCall",
            "GET",
            "/originate",
            Map.of("key", "query"),
            null);

    public static final RawOperation ORIGINATE_CALL_POST = new RawOperation(
            "originateCallPost",
            "POST",
            "/originate",
            Map.of("key", "query"),
            null);

    public static final RawOperation TRANSFER_CALL = new RawOperation(
            "transferCall",
            "GET",
            "/transfer/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation TRANSFER_CALL_POST = new RawOperation(
            "transferCallPost",
            "POST",
            "/transfer",
            Map.of("key", "query"),
            null);

    public static final RawOperation UPDATE_ANNOUNCEMENT = new RawOperation(
            "updateAnnouncement",
            "PATCH",
            "/announcements/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation UPDATE_CONTACT = new RawOperation(
            "updateContact",
            "PATCH",
            "/contacts/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation UPDATE_CONTACT_GROUP = new RawOperation(
            "updateContactGroup",
            "PATCH",
            "/contact_groups/{id}",
            Map.of("key", "query"),
            null);

    public static final RawOperation UPDATE_CRM_INTEGRATIONS = new RawOperation(
            "updateCrmIntegrations",
            "POST",
            "/crm_integrations",
            Map.of("key", "query"),
            null);

    public static final RawOperation UPDATE_IVR_CAMPAIGN = new RawOperation(
            "updateIvrCampaign",
            "PATCH",
            "/ivr_campaigns/{id}.json",
            Map.of("key", "query"),
            null);

    public static final RawOperation UPDATE_OUTBOUND_CALLER_ID = new RawOperation(
            "updateOutboundCallerId",
            "GET",
            "/update_outbound_caller_id",
            Map.of("key", "query"),
            null);

    public static final RawOperation WEBHOOK_PAYLOAD_EXAMPLES = new RawOperation(
            "webhookPayloadExamples",
            "GET",
            "/webhook-payload-examples",
            Map.of(),
            null);

    public static final List<RawOperation> ALL = List.of(
            ANSWER_CALL,
            ANSWER_CALL_POST,
            CREATE_ANNOUNCEMENT,
            CREATE_BLOCKED_NUMBER,
            CREATE_BRIDGE,
            CREATE_CONTACT,
            CREATE_CONTACT_GROUP,
            CREATE_DND,
            CREATE_FAX_DOCUMENT_URL,
            CREATE_FAX_ORDER,
            CREATE_IVR_CAMPAIGN,
            CREATE_RECORDING_URL,
            CREATE_VOICEMAIL_RECORDING_URL,
            CREATE_WEBPHONE_TOKEN,
            DELETE_ANNOUNCEMENT,
            DELETE_BLOCKED_NUMBER,
            DELETE_CONTACT,
            DELETE_CONTACT_GROUP,
            DELETE_IVR_CAMPAIGN,
            DOWNLOAD_FAX_DOCUMENT,
            GET_ANNOUNCEMENTS,
            GET_CALLER_IDS,
            GET_CDR,
            GET_CDRS,
            GET_CRM_INTEGRATIONS,
            GET_EXTENSION,
            GET_QUEUE_USER_LIST,
            GET_QUEUES,
            GET_QUEUES_PENDING,
            GET_VOICEMAIL_MESSAGES,
            HANGUP_CALL,
            LIST_AGENT_STATUSES,
            LIST_BLOCKED_NUMBERS,
            LIST_CONTACT_GROUPS,
            LIST_CONTACTS,
            LIST_EXTENSIONS,
            LIST_FAX_ORDERS,
            LIST_FDRS,
            LIST_USER_STATUSES,
            MANAGE_QUEUE_USERS,
            MUTE_CALL,
            ORIGINATE_CALL,
            ORIGINATE_CALL_POST,
            TRANSFER_CALL,
            TRANSFER_CALL_POST,
            UPDATE_ANNOUNCEMENT,
            UPDATE_CONTACT,
            UPDATE_CONTACT_GROUP,
            UPDATE_CRM_INTEGRATIONS,
            UPDATE_IVR_CAMPAIGN,
            UPDATE_OUTBOUND_CALLER_ID,
            WEBHOOK_PAYLOAD_EXAMPLES);

    private RawOperations() {
    }
}
