// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.switchapi.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class RecordsService {
    private final ProductCore core;

    RecordsService(ProductCore core) {
        this.core = core;
    }

    /** POST /recording_url */
    public String createRecordingUrl(String callUuid) throws IOException, InterruptedException {
        Objects.requireNonNull(callUuid, "callUuid");
        CallParts call = new CallParts();
        call.query("call_uuid", callUuid);
        TransportResponse reply = core.send(RawOperations.CREATE_RECORDING_URL, call);
        return ResponseReader.text(reply);
    }

    /** POST /voicemail_recording_url */
    public String createVoicemailRecordingUrl(String uuid) throws IOException, InterruptedException {
        Objects.requireNonNull(uuid, "uuid");
        CallParts call = new CallParts();
        call.query("uuid", uuid);
        TransportResponse reply = core.send(RawOperations.CREATE_VOICEMAIL_RECORDING_URL, call);
        return ResponseReader.text(reply);
    }

    /** GET /cdrs/{id} */
    public GetCdr200Response getCdr(String id) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        CallParts call = new CallParts();
        call.path("id", id);
        TransportResponse reply = core.send(RawOperations.GET_CDR, call);
        return ResponseReader.json(reply, GetCdr200Response.class);
    }

    /** GET /cdrs */
    public GetCdrs200Response listCdrs(@Nullable String startStampFrom, @Nullable String startStampTo, @Nullable String recordingPresent, @Nullable String direction, @Nullable String callerIdNumber, @Nullable String destinationNumber, @Nullable String missed, @Nullable String queue, @Nullable Long page, @Nullable Long limit) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("start_stamp_from", startStampFrom);
        call.query("start_stamp_to", startStampTo);
        call.query("recording_present", recordingPresent);
        call.query("direction", direction);
        call.query("caller_id_number", callerIdNumber);
        call.query("destination_number", destinationNumber);
        call.query("missed", missed);
        call.query("queue", queue);
        call.query("page", page);
        call.query("limit", limit);
        TransportResponse reply = core.send(RawOperations.GET_CDRS, call);
        return ResponseReader.json(reply, GetCdrs200Response.class);
    }

    /** GET /cdrs without the optional parameters. */
    public GetCdrs200Response listCdrs() throws IOException, InterruptedException {
        return listCdrs(null, null, null, null, null, null, null, null, null, null);
    }

    /** GET /voicemail_messages */
    public GetVoicemailMessages200Response listVoicemailMessages(@Nullable String startStampFrom, @Nullable String startStampTo, @Nullable String read, @Nullable String userNumber, @Nullable String uuid, @Nullable Long page, @Nullable Long limit) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("start_stamp_from", startStampFrom);
        call.query("start_stamp_to", startStampTo);
        call.query("read", read);
        call.query("user_number", userNumber);
        call.query("uuid", uuid);
        call.query("page", page);
        call.query("limit", limit);
        TransportResponse reply = core.send(RawOperations.GET_VOICEMAIL_MESSAGES, call);
        return ResponseReader.json(reply, GetVoicemailMessages200Response.class);
    }

    /** GET /voicemail_messages without the optional parameters. */
    public GetVoicemailMessages200Response listVoicemailMessages() throws IOException, InterruptedException {
        return listVoicemailMessages(null, null, null, null, null, null, null);
    }
}
