// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.RawClient;
import com.bariscemant.verimor.internal.ProductCore;

public abstract class SwitchClientBase {
    private final RawClient raw;
    private final AnnouncementsService announcements;
    private final BlacklistService blacklist;
    private final CallerIdsService callerIds;
    private final CallsService calls;
    private final ContactsService contacts;
    private final CrmService crm;
    private final FaxService fax;
    private final IvrCampaignsService ivrCampaigns;
    private final QueuesService queues;
    private final RecordsService records;
    private final UsersService users;

    protected SwitchClientBase(ProductCore core) {
        this.raw = new RawClient(core, RawOperations.ALL);
        this.announcements = new AnnouncementsService(core);
        this.blacklist = new BlacklistService(core);
        this.callerIds = new CallerIdsService(core);
        this.calls = new CallsService(core);
        this.contacts = new ContactsService(core);
        this.crm = new CrmService(core);
        this.fax = new FaxService(core);
        this.ivrCampaigns = new IvrCampaignsService(core);
        this.queues = new QueuesService(core);
        this.records = new RecordsService(core);
        this.users = new UsersService(core);
    }

    public RawClient raw() {
        return raw;
    }

    public AnnouncementsService announcements() {
        return announcements;
    }

    public BlacklistService blacklist() {
        return blacklist;
    }

    public CallerIdsService callerIds() {
        return callerIds;
    }

    public CallsService calls() {
        return calls;
    }

    public ContactsService contacts() {
        return contacts;
    }

    public CrmService crm() {
        return crm;
    }

    public FaxService fax() {
        return fax;
    }

    public IvrCampaignsService ivrCampaigns() {
        return ivrCampaigns;
    }

    public QueuesService queues() {
        return queues;
    }

    public RecordsService records() {
        return records;
    }

    public UsersService users() {
        return users;
    }
}
