// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.switchapi.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.switchapi.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class UsersService {
    private final ProductCore core;

    UsersService(ProductCore core) {
        this.core = core;
    }

    /** POST /webphone_tokens */
    public String createWebphoneToken(String extension) throws IOException, InterruptedException {
        Objects.requireNonNull(extension, "extension");
        CallParts call = new CallParts();
        call.query("extension", extension);
        TransportResponse reply = core.send(RawOperations.CREATE_WEBPHONE_TOKEN, call);
        return ResponseReader.text(reply);
    }

    /** GET /extensions/{id} */
    public GetExtension200Response getExtension(String id) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        CallParts call = new CallParts();
        call.path("id", id);
        TransportResponse reply = core.send(RawOperations.GET_EXTENSION, call);
        return ResponseReader.json(reply, GetExtension200Response.class);
    }

    /** GET /agent_statuses */
    public List<ListAgentStatuses200ResponseInner> listAgentStatuses(@Nullable String agent, @Nullable String queue, @Nullable String status) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("agent", agent);
        call.query("queue", queue);
        call.query("status", status);
        TransportResponse reply = core.send(RawOperations.LIST_AGENT_STATUSES, call);
        return ResponseReader.json(reply, new TypeReference<List<ListAgentStatuses200ResponseInner>>() { });
    }

    /** GET /agent_statuses without the optional parameters. */
    public List<ListAgentStatuses200ResponseInner> listAgentStatuses() throws IOException, InterruptedException {
        return listAgentStatuses(null, null, null);
    }

    /** GET /extensions */
    public List<ListExtensions200ResponseInner> listExtensions() throws IOException, InterruptedException {
        CallParts call = new CallParts();
        TransportResponse reply = core.send(RawOperations.LIST_EXTENSIONS, call);
        return ResponseReader.json(reply, new TypeReference<List<ListExtensions200ResponseInner>>() { });
    }

    /** GET /user_statuses */
    public List<ListUserStatuses200ResponseInner> listUserStatuses(@Nullable String user, @Nullable String status) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("user", user);
        call.query("status", status);
        TransportResponse reply = core.send(RawOperations.LIST_USER_STATUSES, call);
        return ResponseReader.json(reply, new TypeReference<List<ListUserStatuses200ResponseInner>>() { });
    }

    /** GET /user_statuses without the optional parameters. */
    public List<ListUserStatuses200ResponseInner> listUserStatuses() throws IOException, InterruptedException {
        return listUserStatuses(null, null);
    }

    /** GET /dnd/{id} */
    public String setDnd(String id, String state) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        Objects.requireNonNull(state, "state");
        CallParts call = new CallParts();
        call.path("id", id);
        call.query("state", state);
        TransportResponse reply = core.send(RawOperations.CREATE_DND, call);
        return ResponseReader.text(reply);
    }
}
