// GET /v1/messages — Mesajları Listele / Ara
// Generated by scripts/facades.py from the Verimor contract. Do not edit.
package examples.operations.whatsapp;

import com.bariscemant.verimor.whatsapp.WhatsAppClient;
import com.bariscemant.verimor.whatsapp.WhatsAppClientOptions;
import java.net.URI;

public final class ListMessagesExample {
    public static void main(String[] args) throws Exception {
        WhatsAppClient client = new WhatsAppClient(new WhatsAppClientOptions(
                env("VERIMOR_WHATSAPP_API_KEY", ""))
                .baseUri(URI.create(env("VERIMOR_BASE_URL", "https://wapi.verimor.com.tr"))));
        System.out.println(client.messages().listMessages());
    }

    private static String env(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }
}
