// POST /v1/messages/bulk — Toplu Şablon Mesajı Gönder
// Generated by scripts/facades.py from the Verimor contract. Do not edit.
package examples.operations.whatsapp;

import com.bariscemant.verimor.whatsapp.WhatsAppClient;
import com.bariscemant.verimor.whatsapp.WhatsAppClientOptions;
import com.bariscemant.verimor.whatsapp.generated.model.BulkMessageRequest;
import com.bariscemant.verimor.whatsapp.generated.model.BulkRecipient;
import java.net.URI;
import java.util.List;

public final class SendBulkExample {
    public static void main(String[] args) throws Exception {
        WhatsAppClient client = new WhatsAppClient(new WhatsAppClientOptions(
                env("VERIMOR_WHATSAPP_API_KEY", ""))
                .baseUri(URI.create(env("VERIMOR_BASE_URL", "https://wapi.verimor.com.tr"))));
        System.out.println(client.messages().sendBulk(
                new BulkMessageRequest()
                    .templateName("odeme_hatirlatici")
                    .recipients(List.of(
                        new BulkRecipient()
                            .to("905001112233")))));
    }

    private static String env(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }
}
