// POST /answer — Çağrıyı Cevaplama (POST)
// Generated by scripts/facades.py from the Verimor contract. Do not edit.
package examples.operations.switchapi;

import com.bariscemant.verimor.switchapi.SwitchClient;
import com.bariscemant.verimor.switchapi.SwitchClientOptions;
import com.bariscemant.verimor.switchapi.generated.model.AnswerCallPostRequest;
import java.net.URI;

public final class AnswerExample {
    public static void main(String[] args) throws Exception {
        SwitchClient client = new SwitchClient(new SwitchClientOptions(
                env("VERIMOR_SWITCH_API_KEY", ""))
                .baseUri(URI.create(env("VERIMOR_BASE_URL", "https://api.bulutsantralim.com"))));
        System.out.println(client.calls().answer(
                new AnswerCallPostRequest()
                    .id("736eaf7e-4cc4-44ab-8dbe-16b18e9618b1")));
    }

    private static String env(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }
}
