// POST /fax_orders — Faks Gönderimi
// Generated by scripts/facades.py from the Verimor contract. Do not edit.
package examples.operations.switchapi;

import com.bariscemant.verimor.switchapi.SwitchClient;
import com.bariscemant.verimor.switchapi.SwitchClientOptions;
import java.net.URI;

public final class CreateFaxOrderExample {
    public static void main(String[] args) throws Exception {
        SwitchClient client = new SwitchClient(new SwitchClientOptions(
                env("VERIMOR_SWITCH_API_KEY", ""))
                .baseUri(URI.create(env("VERIMOR_BASE_URL", "https://api.bulutsantralim.com"))));
        System.out.println(client.fax().createFaxOrder("901234567891", "JVBERi0xLjQK"));
    }

    private static String env(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }
}
