// POST /ivr_campaigns.json — Otomatik Arama Kampanyası Oluşturma
// Generated by scripts/facades.py from the Verimor contract. Do not edit.
package examples.operations.switchapi;

import com.bariscemant.verimor.switchapi.SwitchClient;
import com.bariscemant.verimor.switchapi.SwitchClientOptions;
import com.bariscemant.verimor.switchapi.generated.model.CreateIvrCampaignRequest;
import com.bariscemant.verimor.switchapi.generated.model.CreateIvrCampaignRequestPhoneListInner;
import java.net.URI;
import java.util.List;

public final class CreateIvrCampaignExample {
    public static void main(String[] args) throws Exception {
        SwitchClient client = new SwitchClient(new SwitchClientOptions(
                env("VERIMOR_SWITCH_API_KEY", ""))
                .baseUri(URI.create(env("VERIMOR_BASE_URL", "https://api.bulutsantralim.com"))));
        System.out.println(client.ivrCampaigns().createIvrCampaign(
                new CreateIvrCampaignRequest()
                    .callType("ivr")
                    .name("Memnuniyet anketi")
                    .phoneList(List.of(
                        new CreateIvrCampaignRequestPhoneListInner()
                            .phone("05111111111")
                            .phrase("#429 12/05/2017 #430 102.45 #431")
                            .lang("tr-TR"),
                        new CreateIvrCampaignRequestPhoneListInner()
                            .phone("05111111112")
                            .phrase("#429 12/05/2017 #430 65.12 #431")
                            .lang("tr-TR")))));
    }

    private static String env(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }
}
