// GET /queue/manage_users — Kuyruğa Dahili Ekleme, Çıkarma veya Yer Değiştirme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.
package examples.operations.switchapi;

import com.bariscemant.verimor.switchapi.SwitchClient;
import com.bariscemant.verimor.switchapi.SwitchClientOptions;
import java.net.URI;

public final class ManageQueueUsersExample {
    public static void main(String[] args) throws Exception {
        SwitchClient client = new SwitchClient(new SwitchClientOptions(
                env("VERIMOR_SWITCH_API_KEY", ""))
                .baseUri(URI.create(env("VERIMOR_BASE_URL", "https://api.bulutsantralim.com"))));
        System.out.println(client.queues().manageQueueUsers("200", "1000,1001,1002"));
    }

    private static String env(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }
}
