// GET /update_outbound_caller_id — Dahilinin Dış Numarasını (Arayan No) Değiştirme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.
package examples.operations.switchapi;

import com.bariscemant.verimor.switchapi.SwitchClient;
import com.bariscemant.verimor.switchapi.SwitchClientOptions;
import java.net.URI;

public final class UpdateOutboundCallerIdExample {
    public static void main(String[] args) throws Exception {
        SwitchClient client = new SwitchClient(new SwitchClientOptions(
                env("VERIMOR_SWITCH_API_KEY", ""))
                .baseUri(URI.create(env("VERIMOR_BASE_URL", "https://api.bulutsantralim.com"))));
        System.out.println(client.callerIds().updateOutboundCallerId("1000", "90850532xxxx"));
    }

    private static String env(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }
}
