// POST /v2/send.json — SMS Gönderme (JSON)
// Generated by scripts/facades.py from the Verimor contract. Do not edit.
package examples.operations.sms;

import com.bariscemant.verimor.sms.SmsClient;
import com.bariscemant.verimor.sms.SmsClientOptions;
import com.bariscemant.verimor.sms.generated.model.SendSmsJsonRequest;
import com.bariscemant.verimor.sms.generated.model.SendSmsJsonRequestMessagesInner;
import java.net.URI;
import java.util.List;

public final class SendExample {
    public static void main(String[] args) throws Exception {
        SmsClient client = new SmsClient(new SmsClientOptions(
                env("VERIMOR_SMS_USERNAME", ""), env("VERIMOR_SMS_PASSWORD", ""))
                .defaultSender(env("VERIMOR_SMS_SENDER", "VERIMOR"))
                .baseUri(URI.create(env("VERIMOR_BASE_URL", "https://sms.verimor.com.tr"))));
        System.out.println(client.campaigns().send(
                new SendSmsJsonRequest()
                    .username("")
                    .password("")
                    .messages(List.of(
                        new SendSmsJsonRequestMessagesInner()
                            .dest("905111111111,905111111112")
                            .msg("Deneme Mesaj")))));
    }

    private static String env(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }
}
