// POST /v2/otp — OTP Gönderme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.
package examples.operations.sms;

import com.bariscemant.verimor.sms.SmsClient;
import com.bariscemant.verimor.sms.SmsClientOptions;
import com.bariscemant.verimor.sms.generated.model.OtpRequest;
import java.net.URI;

public final class SendOtpExample {
    public static void main(String[] args) throws Exception {
        SmsClient client = new SmsClient(new SmsClientOptions(
                env("VERIMOR_SMS_USERNAME", ""), env("VERIMOR_SMS_PASSWORD", ""))
                .defaultSender(env("VERIMOR_SMS_SENDER", "VERIMOR"))
                .baseUri(URI.create(env("VERIMOR_BASE_URL", "https://sms.verimor.com.tr"))));
        System.out.println(client.campaigns().sendOtp(
                new OtpRequest()
                    .username("")
                    .password("")
                    .dest("905001234567")
                    .code("482931")));
    }

    private static String env(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }
}
