// POST /v2/iys_consents.json — İzin Yönetimi
// Generated by scripts/facades.py from the Verimor contract. Do not edit.
package examples.operations.sms;

import com.bariscemant.verimor.sms.SmsClient;
import com.bariscemant.verimor.sms.SmsClientOptions;
import com.bariscemant.verimor.sms.generated.model.PostV2IysConsentsJsonRequest;
import com.bariscemant.verimor.sms.generated.model.PostV2IysConsentsJsonRequestConsentsInner;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.List;

public final class SubmitIysConsentsExample {
    public static void main(String[] args) throws Exception {
        SmsClient client = new SmsClient(new SmsClientOptions(
                env("VERIMOR_SMS_USERNAME", ""), env("VERIMOR_SMS_PASSWORD", ""))
                .defaultSender(env("VERIMOR_SMS_SENDER", "VERIMOR"))
                .baseUri(URI.create(env("VERIMOR_BASE_URL", "https://sms.verimor.com.tr"))));
        System.out.println(client.iys().submitIysConsents(
                new PostV2IysConsentsJsonRequest()
                    .username("")
                    .password("")
                    .sourceAddr(env("VERIMOR_SMS_SENDER", "VERIMOR"))
                    .consents(List.of(
                        new PostV2IysConsentsJsonRequestConsentsInner()
                            .type("MESAJ")
                            .source("HS_WEB")
                            .status("ONAY")
                            .recipientType("BIREYSEL")
                            .consentDate(OffsetDateTime.parse("2022-04-14T13:30:30+03:00"))
                            .recipient("905001112233")))));
    }

    private static String env(String name, String fallback) {
        String value = System.getenv(name);
        return value == null ? fallback : value;
    }
}
