// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.whatsapp.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.whatsapp.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class HealthService {
    private final ProductCore core;

    HealthService(ProductCore core) {
        this.core = core;
    }

    /** GET /health */
    public JsonNode health() throws IOException, InterruptedException {
        CallParts call = new CallParts();
        TransportResponse reply = core.send(RawOperations.HEALTH_HEALTH_GET, call);
        return ResponseReader.element(reply);
    }
}
