// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.whatsapp.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.whatsapp.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class MessagesService {
    private final ProductCore core;

    MessagesService(ProductCore core) {
        this.core = core;
    }

    /** POST /v1/messages/otp */
    public MessageResponse sendOtp(TemplateMessageRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.SEND_OTP_V1_MESSAGES_OTP_POST, call);
        return ResponseReader.json(reply, MessageResponse.class);
    }

    /** POST /v1/messages/utility */
    public MessageResponse sendUtility(TemplateMessageRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.SEND_UTILITY_V1_MESSAGES_UTILITY_POST, call);
        return ResponseReader.json(reply, MessageResponse.class);
    }
}
