// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.whatsapp.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.whatsapp.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class MessagesService {
    private final ProductCore core;

    MessagesService(ProductCore core) {
        this.core = core;
    }

    /** GET /v1/messages/{message_ref} */
    public MessageDetailResponse getMessage(String messageRef) throws IOException, InterruptedException {
        Objects.requireNonNull(messageRef, "messageRef");
        CallParts call = new CallParts();
        call.path("message_ref", messageRef);
        TransportResponse reply = core.send(RawOperations.GET_MESSAGE_V1_MESSAGES_MESSAGE_REF_GET, call);
        return ResponseReader.json(reply, MessageDetailResponse.class);
    }

    /** GET /v1/messages */
    public MessageListResponse listMessages(@Nullable String to, @Nullable String waMessageId, @Nullable String status, @Nullable String category, @Nullable String templateName, @Nullable String since, @Nullable String until, @Nullable Long limit, @Nullable Long offset) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("to", to);
        call.query("wa_message_id", waMessageId);
        call.query("status", status);
        call.query("category", category);
        call.query("template_name", templateName);
        call.query("since", since);
        call.query("until", until);
        call.query("limit", limit);
        call.query("offset", offset);
        TransportResponse reply = core.send(RawOperations.LIST_MESSAGES_V1_MESSAGES_GET, call);
        return ResponseReader.json(reply, MessageListResponse.class);
    }

    /** GET /v1/messages without the optional parameters. */
    public MessageListResponse listMessages() throws IOException, InterruptedException {
        return listMessages(null, null, null, null, null, null, null, null, null);
    }

    /** POST /v1/messages/bulk */
    public MessageResponse sendBulk(BulkMessageRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.SEND_BULK_V1_MESSAGES_BULK_POST, call);
        return ResponseReader.json(reply, MessageResponse.class);
    }

    /** POST /v1/messages/otp */
    public MessageResponse sendOtp(TemplateMessageRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.SEND_OTP_V1_MESSAGES_OTP_POST, call);
        return ResponseReader.json(reply, MessageResponse.class);
    }

    /** POST /v1/messages/utility */
    public MessageResponse sendUtility(TemplateMessageRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.SEND_UTILITY_V1_MESSAGES_UTILITY_POST, call);
        return ResponseReader.json(reply, MessageResponse.class);
    }
}
