// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.whatsapp.service;

import com.bariscemant.verimor.RawClient;
import com.bariscemant.verimor.internal.ProductCore;

public abstract class WhatsAppClientBase {
    private final RawClient raw;
    private final HealthService health;
    private final MessagesService messages;

    protected WhatsAppClientBase(ProductCore core) {
        this.raw = new RawClient(core, RawOperations.ALL);
        this.health = new HealthService(core);
        this.messages = new MessagesService(core);
    }

    public RawClient raw() {
        return raw;
    }

    public HealthService health() {
        return health;
    }

    public MessagesService messages() {
        return messages;
    }
}
