// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.sms.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.sms.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class BlacklistService {
    private final ProductCore core;

    BlacklistService(ProductCore core) {
        this.core = core;
    }

    /** POST /v2/blacklists */
    public String addBlacklistEntry(String phones) throws IOException, InterruptedException {
        Objects.requireNonNull(phones, "phones");
        CallParts call = new CallParts();
        call.query("phones", phones);
        TransportResponse reply = core.send(RawOperations.POST_V2_BLACKLISTS, call);
        return ResponseReader.text(reply);
    }

    /** DELETE /v2/blacklists/{id} */
    public String deleteBlacklistEntry(String id) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        CallParts call = new CallParts();
        call.path("id", id);
        TransportResponse reply = core.send(RawOperations.DELETE_V2_BLACKLISTS_ID, call);
        return ResponseReader.text(reply);
    }

    /** GET /v2/blacklists */
    public GetV2Blacklists200Response listBlacklistEntries(@Nullable Long offset, @Nullable Long limit) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("offset", offset);
        call.query("limit", limit);
        TransportResponse reply = core.send(RawOperations.GET_V2_BLACKLISTS, call);
        return ResponseReader.json(reply, GetV2Blacklists200Response.class);
    }

    /** GET /v2/blacklists without the optional parameters. */
    public GetV2Blacklists200Response listBlacklistEntries() throws IOException, InterruptedException {
        return listBlacklistEntries(null, null);
    }
}
