// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.sms.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.sms.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class CampaignsService {
    private final ProductCore core;

    CampaignsService(ProductCore core) {
        this.core = core;
    }

    /** POST /v2/cancel/{id} */
    public String cancel(String id, PostV2CancelIdRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(id, "id");
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.path("id", id);
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.POST_V2_CANCEL_ID, call);
        return ResponseReader.text(reply);
    }

    /** POST /v2/send.json */
    public String send(SendSmsJsonRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.SEND_SMS_JSON, call);
        return ResponseReader.text(reply);
    }

    /** GET /v2/send */
    public String sendLegacy(String dest, String msg, @Nullable String sourceAddr, @Nullable String validFor, @Nullable Long datacoding, @Nullable Boolean isCommercial, @Nullable String iysRecipientType, @Nullable String sendAt) throws IOException, InterruptedException {
        Objects.requireNonNull(dest, "dest");
        Objects.requireNonNull(msg, "msg");
        CallParts call = new CallParts();
        call.query("dest", dest);
        call.query("msg", msg);
        call.query("source_addr", sourceAddr);
        call.query("valid_for", validFor);
        call.query("datacoding", datacoding);
        call.query("is_commercial", isCommercial);
        call.query("iys_recipient_type", iysRecipientType);
        call.query("send_at", sendAt);
        TransportResponse reply = core.send(RawOperations.GET_V2_SEND, call);
        return ResponseReader.text(reply);
    }

    /** GET /v2/send without the optional parameters. */
    public String sendLegacy(String dest, String msg) throws IOException, InterruptedException {
        return sendLegacy(dest, msg, null, null, null, null, null, null);
    }

    /** POST /v2/otp */
    public String sendOtp(OtpRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.SEND_OTP, call);
        return ResponseReader.text(reply);
    }
}
