// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.sms.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.sms.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class IysService {
    private final ProductCore core;

    IysService(ProductCore core) {
        this.core = core;
    }

    /** GET /v2/iys/campaigns/{id}/consents */
    public GetV2IysCampaignsIdConsents200Response listIysCampaignConsents(long id, @Nullable Long offset, @Nullable Long limit) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.path("id", id);
        call.query("offset", offset);
        call.query("limit", limit);
        TransportResponse reply = core.send(RawOperations.GET_V2_IYS_CAMPAIGNS_ID_CONSENTS, call);
        return ResponseReader.json(reply, GetV2IysCampaignsIdConsents200Response.class);
    }

    /** GET /v2/iys/campaigns/{id}/consents without the optional parameters. */
    public GetV2IysCampaignsIdConsents200Response listIysCampaignConsents(long id) throws IOException, InterruptedException {
        return listIysCampaignConsents(id, null, null);
    }

    /** GET /v2/iys/campaigns */
    public GetV2IysCampaigns200Response listIysCampaigns(@Nullable Long offset, @Nullable Long limit, @Nullable String source) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("offset", offset);
        call.query("limit", limit);
        call.query("source", source);
        TransportResponse reply = core.send(RawOperations.GET_V2_IYS_CAMPAIGNS, call);
        return ResponseReader.json(reply, GetV2IysCampaigns200Response.class);
    }

    /** GET /v2/iys/campaigns without the optional parameters. */
    public GetV2IysCampaigns200Response listIysCampaigns() throws IOException, InterruptedException {
        return listIysCampaigns(null, null, null);
    }

    /** POST /v2/iys_consents.json */
    public String submitIysConsents(PostV2IysConsentsJsonRequest request) throws IOException, InterruptedException {
        Objects.requireNonNull(request, "request");
        CallParts call = new CallParts();
        call.jsonBody(VerimorJson.serialize(request));
        TransportResponse reply = core.send(RawOperations.POST_V2_IYS_CONSENTS_JSON, call);
        return ResponseReader.text(reply);
    }
}
