// Generated by the Verimor SDK generator. Do not edit.
/** Generated services; parameters are non-null unless marked @Nullable. */
@ParametersAreNonnullByDefault
package com.bariscemant.verimor.sms.service;

import javax.annotation.ParametersAreNonnullByDefault;
