// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.sms.service;

import com.bariscemant.verimor.RawOperation;
import java.net.URI;
import java.util.List;
import java.util.Map;

public final class RawOperations {
    public static final URI DEFAULT_BASE_URI = URI.create("https://sms.verimor.com.tr/");

    public static final RawOperation DELETE_V2_BLACKLISTS_ID = new RawOperation(
            "delete_v2_blacklists_id",
            "DELETE",
            "/v2/blacklists/{id}",
            Map.of("password", "query", "username", "query"),
            null);

    public static final RawOperation GET_SMS_STATUS = new RawOperation(
            "getSmsStatus",
            "GET",
            "/v2/status",
            Map.of("password", "query", "username", "query"),
            null);

    public static final RawOperation GET_V2_BALANCE = new RawOperation(
            "get_v2_balance",
            "GET",
            "/v2/balance",
            Map.of("password", "query", "username", "query"),
            null);

    public static final RawOperation GET_V2_BLACKLISTS = new RawOperation(
            "get_v2_blacklists",
            "GET",
            "/v2/blacklists",
            Map.of("password", "query", "username", "query"),
            null);

    public static final RawOperation GET_V2_HEADERS = new RawOperation(
            "get_v2_headers",
            "GET",
            "/v2/headers",
            Map.of("password", "query", "username", "query"),
            null);

    public static final RawOperation GET_V2_INBOUND_MESSAGES = new RawOperation(
            "get_v2_inbound_messages",
            "GET",
            "/v2/inbound_messages",
            Map.of("password", "query", "username", "query"),
            null);

    public static final RawOperation GET_V2_IYS_CAMPAIGNS = new RawOperation(
            "get_v2_iys_campaigns",
            "GET",
            "/v2/iys/campaigns",
            Map.of("password", "query", "username", "query"),
            null);

    public static final RawOperation GET_V2_IYS_CAMPAIGNS_ID_CONSENTS = new RawOperation(
            "get_v2_iys_campaigns_id_consents",
            "GET",
            "/v2/iys/campaigns/{id}/consents",
            Map.of("password", "query", "username", "query"),
            null);

    public static final RawOperation GET_V2_SEND = new RawOperation(
            "get_v2_send",
            "GET",
            "/v2/send",
            Map.of("password", "query", "username", "query"),
            "query");

    public static final RawOperation POST_V2_BLACKLISTS = new RawOperation(
            "post_v2_blacklists",
            "POST",
            "/v2/blacklists",
            Map.of("password", "query", "username", "query"),
            null);

    public static final RawOperation POST_V2_CANCEL_ID = new RawOperation(
            "post_v2_cancel_id",
            "POST",
            "/v2/cancel/{id}",
            Map.of("password", "body", "username", "body"),
            null);

    public static final RawOperation POST_V2_IYS_CONSENTS_JSON = new RawOperation(
            "post_v2_iys_consents_json",
            "POST",
            "/v2/iys_consents.json",
            Map.of("password", "body", "username", "body"),
            "body");

    public static final RawOperation SEND_SMS_JSON = new RawOperation(
            "sendSmsJson",
            "POST",
            "/v2/send.json",
            Map.of("password", "body", "username", "body"),
            "body");

    public static final List<RawOperation> ALL = List.of(
            DELETE_V2_BLACKLISTS_ID,
            GET_SMS_STATUS,
            GET_V2_BALANCE,
            GET_V2_BLACKLISTS,
            GET_V2_HEADERS,
            GET_V2_INBOUND_MESSAGES,
            GET_V2_IYS_CAMPAIGNS,
            GET_V2_IYS_CAMPAIGNS_ID_CONSENTS,
            GET_V2_SEND,
            POST_V2_BLACKLISTS,
            POST_V2_CANCEL_ID,
            POST_V2_IYS_CONSENTS_JSON,
            SEND_SMS_JSON);

    private RawOperations() {
    }
}
