// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.sms.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.sms.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class ReportsService {
    private final ProductCore core;

    ReportsService(ProductCore core) {
        this.core = core;
    }

    /** GET /v2/inbound_messages */
    public List<GetV2InboundMessages200ResponseInner> listInboundMessages(@Nullable String fromTime, @Nullable String toTime, @Nullable Long greaterThan) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("from_time", fromTime);
        call.query("to_time", toTime);
        call.query("greater_than", greaterThan);
        TransportResponse reply = core.send(RawOperations.GET_V2_INBOUND_MESSAGES, call);
        return ResponseReader.json(reply, new TypeReference<List<GetV2InboundMessages200ResponseInner>>() { });
    }

    /** GET /v2/inbound_messages without the optional parameters. */
    public List<GetV2InboundMessages200ResponseInner> listInboundMessages() throws IOException, InterruptedException {
        return listInboundMessages(null, null, null);
    }

    /** GET /v2/status */
    public List<GetSmsStatus200ResponseInner> status(@Nullable Long id, @Nullable String dest, @Nullable Long greaterThan, @Nullable String customId) throws IOException, InterruptedException {
        CallParts call = new CallParts();
        call.query("id", id);
        call.query("dest", dest);
        call.query("greater_than", greaterThan);
        call.query("custom_id", customId);
        TransportResponse reply = core.send(RawOperations.GET_SMS_STATUS, call);
        return ResponseReader.json(reply, new TypeReference<List<GetSmsStatus200ResponseInner>>() { });
    }

    /** GET /v2/status without the optional parameters. */
    public List<GetSmsStatus200ResponseInner> status() throws IOException, InterruptedException {
        return status(null, null, null, null);
    }
}
