// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.sms.service;

import com.bariscemant.verimor.internal.CallParts;
import com.bariscemant.verimor.internal.ProductCore;
import com.bariscemant.verimor.internal.ResponseReader;
import com.bariscemant.verimor.internal.TransportResponse;
import com.bariscemant.verimor.internal.VerimorJson;
import com.bariscemant.verimor.sms.generated.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

public final class SenderIdsService {
    private final ProductCore core;

    SenderIdsService(ProductCore core) {
        this.core = core;
    }

    /** GET /v2/headers */
    public List<String> listSenderIds() throws IOException, InterruptedException {
        CallParts call = new CallParts();
        TransportResponse reply = core.send(RawOperations.GET_V2_HEADERS, call);
        return ResponseReader.json(reply, new TypeReference<List<String>>() { });
    }
}
