// Generated by the Verimor SDK generator. Do not edit.
package com.bariscemant.verimor.sms.service;

import com.bariscemant.verimor.RawClient;
import com.bariscemant.verimor.internal.ProductCore;

public abstract class SmsClientBase {
    private final RawClient raw;
    private final BalancesService balances;
    private final BlacklistService blacklist;
    private final CampaignsService campaigns;
    private final IysService iys;
    private final ReportsService reports;
    private final SenderIdsService senderIds;

    protected SmsClientBase(ProductCore core) {
        this.raw = new RawClient(core, RawOperations.ALL);
        this.balances = new BalancesService(core);
        this.blacklist = new BlacklistService(core);
        this.campaigns = new CampaignsService(core);
        this.iys = new IysService(core);
        this.reports = new ReportsService(core);
        this.senderIds = new SenderIdsService(core);
    }

    public RawClient raw() {
        return raw;
    }

    public BalancesService balances() {
        return balances;
    }

    public BlacklistService blacklist() {
        return blacklist;
    }

    public CampaignsService campaigns() {
        return campaigns;
    }

    public IysService iys() {
        return iys;
    }

    public ReportsService reports() {
        return reports;
    }

    public SenderIdsService senderIds() {
        return senderIds;
    }
}
